'use client';
import { useEffect, useMemo, useState } from 'react';
type Day={date:string;occupancy:number;pickup7d:number;previous7dPickup:number;paceDelta:number;action:'INCREASE'|'DECREASE'|'HOLD';adjustmentPercent:number;confidence:string;reason:string};
type Approval={id:string;effectiveDate:string;action:string;status:string;reason?:string};
export default function PricingPage(){
 const [propertyId,setPropertyId]=useState(''); const [days,setDays]=useState<Day[]>([]); const [approvals,setApprovals]=useState<Approval[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [selected,setSelected]=useState<Day|null>(null);
 async function load(){setLoading(true);setError('');try{const pRes=await fetch('/api/host/properties',{credentials:'include'});const raw=await pRes.json();const p=Array.isArray(raw)?raw[0]:raw?.data?.[0]||raw?.properties?.[0];if(!p?.id){setDays([]);return}setPropertyId(p.id);const [r,a]=await Promise.all([fetch('/api/host/revenue-recommendations/'+p.id,{credentials:'include'}),fetch('/api/host/pricing-approvals/'+p.id,{credentials:'include'})]);if(!r.ok)throw new Error('Could not load pricing intelligence');setDays((await r.json()).days||[]);setApprovals(a.ok?(await a.json()):[])}catch(e){setError(e instanceof Error?e.message:'Unable to load pricing workspace')}finally{setLoading(false)}}
 useEffect(()=>{load()},[]); const summary=useMemo(()=>({increase:days.filter(d=>d.action==='INCREASE').length,hold:days.filter(d=>d.action==='HOLD').length,decrease:days.filter(d=>d.action==='DECREASE').length}),[days]);
 async function approve(d:Day){if(!propertyId)return;await fetch('/api/host/pricing-approvals/'+propertyId,{method:'POST',headers:{'content-type':'application/json'},credentials:'include',body:JSON.stringify({effectiveDate:d.date,previousPrice:0,proposedPrice:0,action:d.action,reason:d.reason})});setSelected(null);await load()}
 return <main className='min-h-screen bg-[#08090c] text-white'><div className='mx-auto max-w-7xl px-6 py-10 lg:px-10'>
 <header className='mb-8 flex flex-col gap-5 md:flex-row md:items-end md:justify-between'><div><p className='text-xs font-semibold uppercase tracking-[.24em] text-white/40'>Revenue OS</p><h1 className='mt-2 text-4xl font-semibold tracking-tight'>Pricing calendar</h1><p className='mt-2 max-w-2xl text-sm text-white/50'>Demand-aware pricing decisions with explicit host approval.</p></div><button onClick={load} className='rounded-full border border-white/10 bg-white/5 px-5 py-2.5 text-sm'>Refresh</button></header>
 {error&&<div className='mb-5 rounded-2xl border border-red-400/20 bg-red-400/5 p-4 text-sm text-red-200'>{error}</div>}
 <section className='mb-6 grid gap-3 sm:grid-cols-3'>{[['Increase',summary.increase],['Hold',summary.hold],['Decrease',summary.decrease]].map(([l,v])=><div key={String(l)} className='rounded-3xl border border-white/10 bg-white/[.035] p-5'><p className='text-sm text-white/45'>{l}</p><p className='mt-2 text-3xl font-semibold'>{v}</p><p className='mt-1 text-xs text-white/30'>next 30 days</p></div>)}</section>
 <section className='overflow-hidden rounded-3xl border border-white/10 bg-white/[.025]'><div className='grid grid-cols-[1.3fr_.7fr_.7fr_.7fr_.9fr] gap-4 border-b border-white/10 px-5 py-4 text-xs uppercase tracking-wider text-white/35'><span>Date</span><span>Occupancy</span><span>Pickup</span><span>Pace</span><span>Decision</span></div>{loading?<div className='p-12 text-center text-sm text-white/40'>Loading pricing intelligence…</div>:days.map(d=><button key={d.date} onClick={()=>setSelected(d)} className='grid w-full grid-cols-[1.3fr_.7fr_.7fr_.7fr_.9fr] gap-4 border-b border-white/5 px-5 py-4 text-left hover:bg-white/[.045]'><span className='font-medium'>{new Date(d.date+'T00:00:00').toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'})}</span><span>{d.occupancy}%</span><span>{d.pickup7d}</span><span className={d.paceDelta>0?'text-emerald-300':d.paceDelta<0?'text-rose-300':'text-white/50'}>{d.paceDelta>0?'+':''}{d.paceDelta}</span><span>{d.action} {d.adjustmentPercent?('· '+Math.abs(d.adjustmentPercent)+'%'):''}</span></button>)}</section>
 <section className='mt-8'><h2 className='mb-3 text-xl font-semibold'>Decision history</h2><div className='space-y-2'>{approvals.slice(0,8).map(a=><div key={a.id} className='flex justify-between rounded-2xl border border-white/10 bg-white/[.025] p-4'><div><p className='text-sm'>{new Date(a.effectiveDate).toLocaleDateString()} · {a.action}</p><p className='text-xs text-white/35'>{a.reason||'Revenue decision'}</p></div><span className='text-xs uppercase text-white/45'>{a.status}</span></div>)}</div></section>
 {selected&&<div className='fixed inset-0 z-50 flex items-end justify-center bg-black/70 p-4 backdrop-blur-sm md:items-center' onClick={()=>setSelected(null)}><div className='w-full max-w-lg rounded-3xl border border-white/10 bg-[#111318] p-6 shadow-2xl' onClick={e=>e.stopPropagation()}><p className='text-xs uppercase tracking-[.2em] text-white/35'>Revenue recommendation</p><h3 className='mt-2 text-2xl font-semibold'>{selected.date}</h3><p className='mt-3 text-sm leading-6 text-white/55'>{selected.reason}</p><div className='mt-5 grid grid-cols-3 gap-2 text-center'><div className='rounded-2xl bg-white/5 p-3'>Occupancy<br/><b>{selected.occupancy}%</b></div><div className='rounded-2xl bg-white/5 p-3'>Pace<br/><b>{selected.paceDelta>0?'+':''}{selected.paceDelta}</b></div><div className='rounded-2xl bg-white/5 p-3'>Confidence<br/><b>{selected.confidence}</b></div></div><div className='mt-6 flex gap-3'><button onClick={()=>setSelected(null)} className='flex-1 rounded-full border border-white/10 px-4 py-3'>Dismiss</button><button onClick={()=>approve(selected)} className='flex-1 rounded-full bg-white px-4 py-3 font-semibold text-black'>Approve recommendation</button></div><p className='mt-3 text-center text-[11px] text-white/25'>Approval records the decision; live price execution remains controlled.</p></div></div>}
 </div></main> }